name: meme-deployment
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} 
      PORT: ${{ PORT }}
      MONGODB_URI: ${{ MONGODB_URI }}
      CLOUDINARY_CLOUD_NAME: ${{ CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ CLOUDINARY_API_SECRET }}
      JWT_SECRET: ${{ JWT_SECRET }}
    steps:
      - name: copying files
        uses: actions/checkout@v2
      - name: creating .env
        run: |
          echo VITE_API_BASE_URL> Frontend/.env
          echo  PORT>> backend/.env
          echo VITE_API_BASE_URL>> backend/.env
          echo VITE_API_BASE_URL>> backend/.env
      - name: ssh into ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
      
        
