name: meme-deployment
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} 
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: copying files
        uses: actions/checkout@v2
      - name: creating .env
        run: |
          echo VITE_API_BASE_URL=$VITE_API_BASE_URL > ./MemePool/Frontend/.env
          
          echo PORT=$PORT > ./MemePool/backend/.env
          echo MONGODB_URI=$MONGODB_URI >> ./MemePool/backend/.env
          echo CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME >> ./MemePool/backend/.env
          echo CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY >> ./MemePool/backend/.env
          echo CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET >> ./MemePool/backend/.en
          echo JWT_SECRET=$JWT_SECRET >> ./MemePool/backend/.env
      - name: ssh into ec2
        uses: appleboy/scp-action@v1
        with:
           host: ${{ secrets.HOST }}
           username:  ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           source: ./MemePool
           target: /home/ubuntu/
      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@v1
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           script: |
             cd /home/ubuntu/MemePool
             docker-compose up  
      
        
